language: node_js

if: tag IS present

node_js:
  - "12.12"

cache:
  npm: false

script:
  - npx gulp

before_deploy:
  - rm -rf .* src layui package*.json node_modules gulpfile.js composer.json
  - tar -czf coolay-${TRAVIS_TAG}.tar.gz ./*
  - zip coolay-${TRAVIS_TAG}.zip ./*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - coolay-${TRAVIS_TAG}.tar.gz
    - coolay-${TRAVIS_TAG}.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
    repo: ninggf/coolayui
    node_js: "12"
